export default  {
    iHome:"home",
    iUser: "user",
    iPicture:"picture",
    iMusic:"customer-service",
    iBook:"book",
    iArrowDown:"down",
    iCode:"code",
    iTime:"clock-circle",
    iLeft:"left",
    iRight:"right",
    iFileText:"file-text",
    iRightCircle:"right-circle",
    iBars:"bars",
    faBackward:"backward",
    faPause:"play-circle",
    faPlay:"pause-circle",
    faForward:"forward",
    faStop:"stop",
    faVolume:"sound",
    faRepeat:"sync",
    faRandom:"swap"
}